on: workflow_call

jobs:
  publish:
    name: Publish to PyPi
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/project/adopt
    steps:
      - name: Clean dist
        run: |
          rm -rf dist/

      - name: Retrieve data
        uses: actions/download-artifact@v4
        with:
          name: wheel
          path: dist/wheel

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/wheel
