# Build and install package and run tests

name: Build test and install

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    name: Build
    uses: ./.github/workflows/_build.yaml
    with:
      python-version: "3.11" # cannot be environment variable, limitation of workflow

  test:
    needs: build
    name: Test
    uses: ./.github/workflows/_test.yaml
    secrets: inherit

  check-tag:
    needs: build
    name: Check
    uses: ./.github/workflows/_check_tag.yaml
    with:
      continue-on-error: true
