# This workflow will upload adopt to PyPI when a release is created

name: Publish and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/_build.yaml
    with:
      python-version: "3.11" # cannot be environment variable, limitation of workflow

  check-tag:
    needs: build
    name: Check
    uses: ./.github/workflows/_check_tag.yaml
    with:
      continue-on-error: false

  publish:
    needs: check-tag
    name: Publish
    uses: ./.github/workflows/_publish.yaml

  release:
    needs: publish
    name: Release
    uses: ./.github/workflows/_release.yaml
    secrets: inherit # inherit all secrets if required for testing
