# This workflow will upload adopt to PyPI when a release is created

name: Publish and Release

# on: workflow_dispatch
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build wheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m build . --outdir _build/wheel

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: _build/wheel

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
    # environment:
    #   name: pypi
    #   url: https://pypi.org/project/adopt

    steps:
      - name: Retrieve wheel
        uses: actions/download-artifact@v4
        with:
          name: wheel
          path: dist/

      # - name: Publish to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     packages-dir: dist/

  release:
    runs-on: ubuntu-latest
    needs: publish
    permissions:
      id-token: write

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Clean dist
        run: |
          rm -rf dist/

      - name: Retrieve wheel
        uses: actions/download-artifact@v4
        with:
          name: wheel
          path: dist/

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pkginfo

      - name: Extract version
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import sys
            from pathlib import Path
            from pkginfo import Wheel

            whl_files = list(Path('dist/').glob('*.whl'))
            whl_versions = [Wheel(str(whl)).version for whl in whl_files]

            if not len(set(whl_versions)) == 1:
                print('Error: All wheels must have the same version')
                sys.exit(1)

            with open('version.txt', 'w') as f:
                f.write(whl_versions[0])

      - name: Store version
        run: |
          echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Echo VERSION
        run: |
          echo $VERSION
        # uses: softprops/action-gh-release@v1
        # with:
        #   files: dist/*
        #   tag_name: ${{ github.event.release.tag_name }}
        #   release_name: ${{ github.event.release.name }}
        #   body: ${{ github.event.release.body }}
        #   draft: false
        #   prerelease: false
        #   token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Create GitHub Release
