# This workflow will upload adopt to PyPI when a release is created

name: Publish Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build wheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m build . --outdir _build/wheel

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: _build/wheel

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/project/adopt/${{ github.event.release.name }}

    steps:
      - name: Retrieve wheel
        uses: actions/download-artifact@v4
        with:
          name: wheel
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
