# This workflow will upload adopt to PyPI when a release is created

name: Publish and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/_build.yaml
    with:
      python-version: "3.11" # cannot be environment variable, limitation of workflow

  check-tag:
    needs: build
    name: Check
    uses: ./.github/workflows/_check_tag.yaml
    with:
      continue-on-error: false

  publish:
    runs-on: ubuntu-latest
    needs: check-tag
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/project/adopt

    steps:
      - name: Clean dist
        run: |
          rm -rf dist/

      - name: Retrieve data
        uses: actions/download-artifact@v4
        with:
          name: wheel
          path: dist/wheel

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/wheel

  release:
    runs-on: ubuntu-latest
    needs: publish
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Clean dist
        run: |
          rm -rf dist/

      - name: Retrieve wheel
        uses: actions/download-artifact@v4
        with:
          name: wheel
          path: dist/wheel

      - name: Retrieve version
        uses: actions/download-artifact@v4
        with:
          name: version
          path: dist/

      - name: Store version
        run: |
          echo "VERSION=$(cat dist/version.txt)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/wheel/*
          name: Release ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          body: Releasing ${{ env.VERSION }} # TODO: Add release notes
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
